# 自定义层

In [1]:
import torch
import torch.nn.functional as F
from torch import nn

## 没有任何参数的自定义层

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, X):
        return X - X.mean()
    
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

将层作为组件合并到构建更复杂的模型中

In [3]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

Y = net(torch.rand(4, 8))
Y.mean()

tensor(2.3283e-09, grad_fn=<MeanBackward0>)

## 带参数的图层

In [8]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units, ))
        
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [9]:
dense = MyLinear(5, 3)
dense.weight

Parameter containing:
tensor([[ 0.7307, -1.1199,  1.0359],
        [-2.2991,  0.1360, -0.6419],
        [-0.5145, -0.7271, -1.1719],
        [-1.1333,  0.2027, -0.4371],
        [ 0.0818,  0.2740,  0.3367]], requires_grad=True)

使用自定义层直接执行正向传播计算

In [18]:
dense(torch.rand(2, 5))

tensor([[0.0000, 0.0000, 0.0000],
        [0.0371, 0.0000, 0.0000]])

使用自定义层构建模型

In [19]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.0000],
        [1.2620]])