In [1]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [2]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [20]:
# 矩阵的转置
A, A.T

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  4.,  8., 12., 16.],
         [ 1.,  5.,  9., 13., 17.],
         [ 2.,  6., 10., 14., 18.],
         [ 3.,  7., 11., 15., 19.]]))

In [4]:
# 对称矩阵，A=AT
B = torch.tensor([[1, 2, 3],
                  [2, 9, 4], 
                  [3, 4, 5]])
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [5]:
# 相同维度tensor进行二元运算不改变形状
A = torch.arange(20 ,dtype=torch.float32).reshape(5, 4)
B = A.clone() # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [6]:
# 两个矩阵按元素对应相乘（哈达玛积）
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [7]:
# 标量与矩阵的运算
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [8]:
# 指定轴求和（求均值等价）
A = torch.arange(20*2).reshape(2, 5, 4)
A_sum_axis0 = A.sum(axis=0)
print(A_sum_axis0, A_sum_axis0.shape)

A_sum_axis1 = A.sum(axis=1)
print(A_sum_axis1, A_sum_axis1.shape)

print(A.sum(axis=[0, 1]), A.sum(axis=[0, 1]).shape)

tensor([[20, 22, 24, 26],
        [28, 30, 32, 34],
        [36, 38, 40, 42],
        [44, 46, 48, 50],
        [52, 54, 56, 58]]) torch.Size([5, 4])
tensor([[ 40,  45,  50,  55],
        [140, 145, 150, 155]]) torch.Size([2, 4])
tensor([180, 190, 200, 210]) torch.Size([4])


In [9]:
# 计算总和或均值时保持轴数不变
A = torch.arange(20 ,dtype=torch.float32).reshape(5, 4)

sum_A = A.sum(axis=1, keepdims = False)
sum_A_keep = A.sum(axis=1, keepdims = True)

sum_A, sum_A.shape, sum_A_keep, sum_A_keep.shape

(tensor([ 6., 22., 38., 54., 70.]),
 torch.Size([5]),
 tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 torch.Size([5, 1]))

In [22]:
# 通过广播计算A / sum_A_keep
print(A.shape, sum_A_keep.shape)
A / sum_A_keep

torch.Size([5, 4]) torch.Size([5, 1])


tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [11]:
# 指定轴进行累加求和
A.cumsum(axis = 0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [12]:
# 点积是相应位置元素的乘积的和
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
print(x, y, torch.dot(x, y))
# 等价于
print(torch.sum(x * y))

tensor([0., 1., 2., 3.]) tensor([1., 1., 1., 1.]) tensor(6.)
tensor(6.)


In [15]:
# 矩阵向量积Ax是一个长度为m的列向量，其第i个元素是点积aiTx
print(A.shape, x.shape)
torch.mv(A, x), torch.mv(A, x).shape

torch.Size([5, 4]) torch.Size([4])


(tensor([ 14.,  38.,  62.,  86., 110.]), torch.Size([5]))

In [16]:
# 矩阵相乘
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [17]:
# L2范数
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [18]:
# L1范数
torch.abs(u).sum()

tensor(7.)

In [19]:
# 矩阵的佛罗贝尼乌斯范数，是矩阵元素的平方和的平方根
torch.norm(torch.ones((4, 9)))

tensor(6.)